name: Python CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-html flake8 flake8-html

      - name: Run tests
        run: |
          pytest --html=test-report.html

      - name: Run flake8
        run: |
          flake8 . --format=html --htmldir=flake-report

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            test-report.html
            flake-report